### ISSUE TITLE
Lesson 15: Issue with getting TokenURIs 

### ISSUE THREAD

**Issue by eugenekhoo1** [PatrickAlphaC/nextjs-nft-marketplace-thegraph-fcc#28]
[Also posted on main repo]

Hi, I am having issues getting the Token URIs using the useWeb3Contract function in NFTBox..as you can see my NFT boxes are not loading due to it being undefined. 

<img width="1111" alt="Screenshot 2023-06-26 at 4 38 18 PM" src="https://github.com/smartcontractkit/full-blockchain-solidity-course-js/assets/115082788/2ad3ffae-1b0b-48fa-9c3b-6cc4d7435e4b">
<img width="515" alt="Screenshot 2023-06-26 at 4 38 32 PM" src="https://github.com/smartcontractkit/full-blockchain-solidity-course-js/assets/115082788/86c897c0-b889-416b-973a-583f65b351b1">

The issue seems to be with the follow code, but i cant seem to debug it:
```
const { runContractFunction: getTokenURI } = useWeb3Contract({
    abi: nftAbi,
    contractAddress: nftAddress,
    functionName: "tokenURI",
    params: {
      tokenId: tokenId,
    },
  });
```

I have checked my subgraph and it does show the correct nftAddress that the getTokenURI function uses as one of it params
<img width="1261" alt="Screenshot 2023-06-26 at 4 41 37 PM" src="https://github.com/smartcontractkit/full-blockchain-solidity-course-js/assets/115082788/9de78775-f108-4661-a966-28cfbd359f22">

I am also able to get the ActiveItems that the 'listings.js' code is calling.
<img width="519" alt="Screenshot 2023-06-26 at 4 44 04 PM" src="https://github.com/smartcontractkit/full-blockchain-solidity-course-js/assets/115082788/a4f78836-7b0f-40e2-b06d-4932d0565e88">

Tried to troubleshoot, but seems like all the params for the useWeb3Contract are in order...so im not too sure what the issue is with loading..

Repos:
NextJS code
https://github.com/eugenekhoo1/nextjs-nft-marketplace

NFT Contracts
https://github.com/eugenekhoo1/hardhat-nft-marketplace

Graph
https://github.com/eugenekhoo1/graph-nft-marketplace

**Comment by helloiampratyush** [comment]
i have resolved this problem..if you  still need then tell..

**Comment by helloiampratyush** [comment]
first of all graph is used for some test network or mainnet so in chainId section do "11155111" instead of  "31337" i don`t think you are going to do it by the way..

**Comment by tusharr1411** [comment]
With
```javascript
const { runContractFunction: getTokenURI } = useWeb3Contract({
    abi: nftAbi,
    contractAddress: nftAddress,
    functionName: "tokenURI",
    params: {
      tokenId: tokenId,
    },
  });
  ```
 you are explicitly telling  `tokenURI` function to accept `tokenId` as a parameter and assign it to `tokenId` variable. However in your  `BasicNFT.sol `contract you have commented out the input `tokenId` in `tokenURI` function implementation so `useWeb3Contract({.....    ,params: {tokenId: tokenId,},})`  never assign it to the `tokenId` variable. So you need to uncomment the input parameter variable of `tokenURI` function in you `BasicNFT` smartcontract.
 So it should be like this
 ```solidity
     function tokenURI(uint256 tokenId) public view override returns (string memory) {
        return TOKEN_URI;
    }
```

**Comment by Shradhesh71** [comment]
Can you help me solve this issue? I am experiencing the same problem. (In nextjs-nft-marketplace-**thegraph**-fcc)
i have also uncomment the parameter variable of tokenURI function in you BasicNFT smartcontract.

![Screenshot 2024-03-05 023937](https://github.com/smartcontractkit/full-blockchain-solidity-course-js/assets/124858873/5ddc8c3b-42b6-4289-892d-4e951373b2aa)

**Comment by Shradhesh71** [comment]
> With
> 
> ```js
> const { runContractFunction: getTokenURI } = useWeb3Contract({
>     abi: nftAbi,
>     contractAddress: nftAddress,
>     functionName: "tokenURI",
>     params: {
>       tokenId: tokenId,
>     },
>   });
> ```
> 
> you are explicitly telling `tokenURI` function to accept `tokenId` as a parameter and assign it to `tokenId` variable. However in your `BasicNFT.sol `contract you have commented out the input `tokenId` in `tokenURI` function implementation so `useWeb3Contract({..... ,params: {tokenId: tokenId,},})` never assign it to the `tokenId` variable. So you need to uncomment the input parameter variable of `tokenURI` function in you `BasicNFT` smartcontract. So it should be like this
> 
> ```solidity
>     function tokenURI(uint256 tokenId) public view override returns (string memory) {
>        return TOKEN_URI;
>    }
> ```

Can you help me solve this issue? I am experiencing the same problem. (In nextjs-nft-marketplace-**thegraph**-fcc)
i have also uncomment the parameter variable of tokenURI function in you BasicNFT smartcontract.

![Screenshot 2024-03-05 023937](https://github.com/smartcontractkit/full-blockchain-solidity-course-js/assets/124858873/5ddc8c3b-42b6-4289-892d-4e951373b2aa)

**Comment by tusharr1411** [comment]
please share your repo

**Comment by Shradhesh71** [comment]
this is my **GraphQL _Nft_MarketPlace** repository: https://github.com/Shradhesh71/GraphQL_NftMarketPlace.git

and this is my **Hardhat_NFT_Marketplace** repository:   https://github.com/Shradhesh71/Nft-MarketPlace.git

**Comment by Shradhesh71** [comment]
When I connect with Hardhat, errors occur; however, when I connect to Sepolia, no errors are shown, and all images are displayed.

When i am Moving blocks... in sepolia network this error are occur:)
ProviderError: Unsupported method: evm_mine. See available methods at https://docs.alchemy.com/alchemy/documentation/apis
    at HttpProvider.request (C:\Users\shrad\Desktop\jgh\hh-BC\hardhat-nft-marketplace\node_modules\hardhat\src\internal\core\providers\http.ts:88:21)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at moveBlocks (C:\Users\shrad\Desktop\jgh\hh-BC\hardhat-nft-marketplace\utils\move-blocks.js:11:9)     
    at mine (C:\Users\shrad\Desktop\jgh\hh-BC\hardhat-nft-marketplace\scripts\mine.js:7:5)
error Command failed with exit code 1.

GraphQL NftMarketPlace repo:  https://github.com/Shradhesh71/GraphQL_NftMarketPlace
Hardhat Nft-MarketPlace repo:  https://github.com/Shradhesh71/Nft-MarketPlace

**Comment by tusharr1411** [comment]
The ```evm_mine``` method used is in ```moveBlocks``` is for hardhat network not for sepolia or real testnet. 

Coming to hardhat, try again with clearing activity and nonce data ( and make sure you're connected to hardhat network in metamask).

One important thing remember is that you can not query your local blockchain(hardhat) with GRAPH indexer.

**Comment by Shradhesh71** [comment]
Thank you @tusharr1411  for helping me with this topic.

**Comment by RajatSinghhh** [comment]
I am getting a list of all the the active item's tokenId,nftAddress and other props which i am passing to nftBox. My question is this as the tokenUri function takes one value as parameter in the form of tokenId but i am getting all the Active TokenId's in tokenId varaible please help.
